backend:
  name: github
  repo: damaraa/bisa
  branch: master # Branch to update (optional; defaults to master)
  base_url: https://auth.sengat.workers.dev/
media_folder: ''
public_folder: ''
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}/index"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "posts"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        default: "/images/default-thumbnail.jpg"
        config:
          filename_field: "featured"
        media_library:
          name: "featured_image"
          config:
            multiple: false
            previewStep: false
            fileEditor: false
          filename: "featured"
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}